[tox]
envlist =
    checkqa,
    py{310, 311, 312}-dj{52}
   
[testenv]
passenv = CI, CIRCLECI, CIRCLE_*
deps =
    coverage<5
    codecov
    dj52: Django>=5.2,<6
    master: https://github.com/django/django/tarball/master

usedevelop = True
commands =
    coverage run setup.py test
    coverage report -m --skip-covered

[testenv:checkqa]
commands =
    flake8 pinax
    isort --recursive --check-only --diff pinax -sp tox.ini
deps =
    flake8 == 3.7.9
    flake8-quotes == 2.1.1
    isort == 4.3.21
